// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// BML
List BML(IntegerMatrix ma, int ntrees, double pthres, int nrep);
RcppExport SEXP _BML_BML(SEXP maSEXP, SEXP ntreesSEXP, SEXP pthresSEXP, SEXP nrepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type ma(maSEXP);
    Rcpp::traits::input_parameter< int >::type ntrees(ntreesSEXP);
    Rcpp::traits::input_parameter< double >::type pthres(pthresSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    rcpp_result_gen = Rcpp::wrap(BML(ma, ntrees, pthres, nrep));
    return rcpp_result_gen;
END_RCPP
}
// writeDotFile
void writeDotFile(List bml, std::string file);
RcppExport SEXP _BML_writeDotFile(SEXP bmlSEXP, SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type bml(bmlSEXP);
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    writeDotFile(bml, file);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BML_BML", (DL_FUNC) &_BML_BML, 4},
    {"_BML_writeDotFile", (DL_FUNC) &_BML_writeDotFile, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BML(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
