# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BML <- function(ma, ntrees, pthres) {
    .Call(`_BML_BML`, ma, ntrees, pthres)
}

